### ISSUE TITLE
Add correct prefix in SASS/HTML template files according to the flag/type

### ISSUE THREAD

**Issue by Maybach91** [martinherweg/modlr#13]
```
// Modul
.m-<%= moduleName.replace('-', '_') %>  {
}
```

The `m` should be the flag/type of the created module. If i create a atom with -a flag, then it should be named .a-Name etc. The same for the html templates. There should be the flag/type variable available.

**Quick-Fix:**
`<%= pathOptions.key.charAt(0) %>-<%= moduleName.replace('-', '_') %>`

**Comment by martinherweg** [comment]
Templates are something the user has full control of and path options aren't always provided so please add this yourself in your projects.
